### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>

### ISSUE THREAD

**Issue by zlwaiwjj** [chrvadala/react-svg-pan-zoom#146] opened 2019-05-23 01:33 UTC
### Bug reports:
Please replace this line with a brief summary of your issue **AND** provide an example that shows a bug using this jsfiddle as template:
https://jsfiddle.net/chrvadala/f67qyfsd/

### Features:
Please replace this line with a brief description of the suggested feature.
I'll consider your request and I'll implement it as long as I have a chance.

------------------------------------------------------------------------------------------
Please consider also to support this project https://beerpay.io/chrvadala/react-svg-pan-zoom

[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>
react-dom.development.js:1575 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312

**Comment by jermspeaks** [comment] 2019-06-25 19:45
This is a duplicate of #141, in case you're still looking for an answer.

**Closed** 2019-10-18 17:12 UTC
